---

name: lint

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@v7.2.0

      - run: |
          uv sync
          make -j mypy

  ruff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@v7.2.0

      - run: |
          uv sync
          make -j ruff

  YAMLLint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v6

      - name: YAMLLint
        uses: karancode/yamllint-github-action@v3.0.0

  markdown-lint:
    name: Lint markdown files.

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: DavidAnson/markdownlint-cli2-action@v23.0.0
